version: "3.1"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
